### ISSUE TITLE
Upload the SVG files as well

### ISSUE THREAD

**Issue by conrad-heimbold** [1C3/ICEcons#6]
Hi 1C3, 

I could not find the mentioned svg files anywhere in the repository that you ( @1C3 ) use for generating the pngs, so it seems like they are not online (correct me if I'm wrong). Could you upload them as well, please? In a directory that is not used for compiling the app, of course... That would make it much easier if you want to edit the pictures. Thanks in advance!

**Comment by conrad-heimbold** [comment]
That would allow you to define an **external cascading style sheet (CSS)** for all **SVG** files.

This way, you can for example **change the colour of all icons at once**. You could make all icons bilious green to make your smartphone look like a hackers phone ;) :D . 

Or you could give all icons at once a **small, black border** to make them still readable **if the app is also white** (white icon on white background can not be seen...). Take for example Barcode Scanner or Seafile. With some hacking and designing you could probably make all apps in the app switcher dark enough, so that the white icons can be seen; but that requires some hacking / knowledge and I do not know how good it works... 

Or you could easily **give every icon its own color**, but only one colour per icon (to preserve the minimalistic look), just by adding an `!important` statement in the CSS file which overrides the color values in the SVG files. 

You see: there are plenty of possibilities what you could do! 

Android supports SVG files natively since API level 21 (Android 5).

**Comment by conrad-heimbold** [comment]
png <-> svg for pictures is a little bit like binary <-> source code for programs. 
Changing a png pixel by pixel is a tedious work. 
Changing a binary program is difficult / impossible in binary form...

**Comment by atmtck** [comment]
Yes the svgs are not in the main repository, that is because I use a series of shell and python scripts to automate converting images from svg to png for the various density buckets and adding icon names to the pack, but it is currently quite messy and not well integrated with the source. I am progressively improving it and my objective is to make it so that you can just run a script and it will convert to png, copy them in the appropriate locations, and add icon names to the necessary files in the source. Btw it already supports changing icon colors, and coloring icons with random colors from a list, so as soon as it is easily usable I will add it to the main repo so people who build from source can choose their own colors. I tried to make it so that you could change the colors from inside the app too but it seems like with the way icon packs work in android it is impossible.

**Comment by atmtck** [comment]
I'll leave this issue open as a reminder for myself

**Comment by conrad-heimbold** [comment]
I would say, this issue should get priority above the other icon requests / suggestions and bug fixes, because it makes improvements (e.g. black borders for white backgrounds, see comments above), collaboration and personal forks (svg files are simple text/xml files which can also be just partly changed, not only as a whole) much easier. Please comment if you do not agree with me!

**Comment by dkanada** [comment]
@1C3 have you looked into this recently? Having the svg files and scripts would be useful, even if the scripts aren't completely finished yet.

**Comment by conrad-heimbold** [comment]
The converting script is pretty simple: 
```
#!/bin/bash
DESIRED_SIZES="32 48 64 72 96 128 144 192 256 384 512" # side length of the square icon in pixels. 
for SIZE in $DESIRED_SIZES
do 
inkscape --export-png=${FILENAME}-${SIZE}x${SIZE}.png --export-width=$SIZE --export-height=$SIZE ${FILENAME}.svg
done
# Now, just some mv / rename / cp of the files to the desired locations. Finished. 
```

**Comment by dkanada** [comment]
I was just mentioning both since in earlier comments it seemed like he was waiting to add the svg files because of incomplete scripts. I agree with what you said earlier, it would be much easier to make slight changes to the icons if we had the svg files and I would love to add some icons that are not currently in the pack, I am not sure if @1C3 still uses github though.

**Comment by conrad-heimbold** [comment]
I am working on replacing the png icons of this repo with svg ones. 14 are already finished.

**Comment by dkanada** [comment]
I also wanted to add [moonshine](https://github.com/natewren/moonshine-iconpack) to F-Droid at some point this summer, we could create a fork of this repository and start working on both if you are interested. I was just going to use the psd files as a source for moonshine, there are probably way too many to convert to a vector format.

**Comment by conrad-heimbold** [comment]
fixed with the fork of this app (https://github.com/dkanada/ICEcons ).
