### ISSUE TITLE
white icons on white settings background

### ISSUE THREAD

**Issue by conrad-heimbold** [1C3/ICEcons#7]
Hi @1C3, what kind of open source cyanogenmod theme do you use to make your white icons visible in the settings app? I could not find any open source one that makes the settings background dark enough (they all make it white...). Do I have to make my own theme? 

(Just like you, I guess, I do NOT want to use ThemeDIY, because it is not open source and takes AWAY most of your rights what you can do with your themes)

**Comment by atmtck** [comment]
I usually use either nova or kiss launchers and apply the theme only launcher-wide, so that the rest of the system keeps using normal icons, so I never searched for a darker theme to make them visible. I guess the best solution would be to add a slight shadow to the icons like I did to the launcher icon of the app to make it visible on fdroid, but it would make the icons look different so I'd have to try it for a bit before making any decision.

**Comment by conrad-heimbold** [comment]
If I have some time again in the future, I think I will make my own theme which makes the settings background dark. It does not sound too difficult, once I have set up Android Studio... I do not like shadows that much, I would prefer to keep the icons single-colored without any color-steps.
